### ISSUE TITLE
bota esse html no index

### ISSUE THREAD

**Issue by davilucasdm** [El0y-C0SM0/Casa-do-Hobbit#6]

**Comment by sscarlate3** [comment]
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="imgs/icon.ico" type="image/x-icon">
    <link rel="stylesheet" href="csszindoscria.css">
    <title>Casa do Hobbit</title>
</head>
<body>
    <div id="inicio" class="move">
        
        <h1 class="initial">Preparado para conhecer o mundo de Rpg!?</h1>
        <button class="explorar" onclick="desaparece()">Explorar</button>
    
    </div>

    <header>
        <img src="imgs/logo.png" alt="logo de D&D5E" id="logo">
    </header>
    
    <nav id="menu">
        <input type="checkbox" id="checkbox-menu">
        <label for="checkbox-menu">
            <span></span>
            <span></span>
            <span></span>
            <div id="lks">
                <ul>
                    <li><h2>Páginas</h2></li>
                    <li><a href="DnD.html" class="sobre">História do D&D</a></li>
                    <li><a href="Regras.html" class="sobre">Regras</a></li>
                    <li><a href="Raças.html" class="sobre">Raças</a></li>
                    <li><a href="Classes.html" class="sobre">Classes</a></li>
                    <li><a href="linksobre" class="sobre">Como criar seu personagem</a></li>
                    <li><h2>Sobre nós</h2></li>
                    <li><a href="https://github.com/El0y-C0SM0/Casa-do-Hobbit" class="sobre">A Casa do Hobbit</a></li>
                    <li><a href="sobreEloy.html" class="sobre">Mestre Eloy, O Ladino</a></li>
                    <li><a href="sobreDavi.html" class="sobre">Mestre Davi, o ...</a></li>
                    <li><a href="sobreDavid.html" class="sobre">Mestre David, o ...</a></li>
                </ul>
            </div>
        </label>
    </nav>
    <main>
        <section id="introdução">
            <h1>Bem Vindo Jovem e Inesperiente Aventureiro!</h1>
            <p>
                Confuso? Bem, nós vamos servir como aquela taverna onde você se reúne com seu grupo para descobrir informações para a sua próxima missão. Primeiro se acomode perto da lareira que vamos para as explicações.
            </p>
        </section>
        <section id="O-que-é-RPG">
            <h1>O que é RPG</h1>
            <h3 class="frases-legais">
                RPG é sobre se deixar levar pela imaginação
            </h3>
            <p>
                O Role Playing Game (RPG) é um jogo de “interpretação de personagens”, como diz a tradução, onde cada jogador da vida a um personagem e um outro jogador “da vida” ao universo onde se passa a história. Esse ultimo jogador mencionado é o “Mestre” e ele é responsável por guiar a história, propor desafios e regrar as ações dos personagens (sim, RPG tem regra, não é bagunça, mas quase) com auxílio do livro. Já os outros jogadores são quem vivenciam a narrativa conforme superam as dificuldades impostas pelo mestre e os dramas de cada personagem. É mesmo, não falei sobre o livro, bem esse é comparável a bíblia do rpgista, é nele que vem detalhada as regras, o universo, os seres e todo o básico para guiar sua aventura.
            </p>
            <h3 class="frases-legais">
                Muitos gostam de dizer que RPG é estruturado por três pilares <strong class="destaque">Exploração, Interação e Combate</strong>
            </h3>
            <p class="nota">
                <strong>Nota:</strong> existem outros tipos de RPG, mas aqui iremos tratar do clássico RPG de mesa
            </p>
        </section>
        <section id="O-que-é-DeD">
            <h1>O que é? Por que D&D?</h1>
            <p>
                Dungeons and Dragons (D&D para os mais íntimos) foi o primeiro RPG criado e é até hoje o mais famoso e mais jogado do mundo. Com forte inspiração nas obras de Tolkien ele está na sua quinta edição e se passa em universo de fantasia medieval com Elfos, Orcs, bruxos e… claro, Dragões. Para saber mais sobre a história de D&D <a href="DnD.html" class="links">clique aqui</a>.
            </p>
            <p>
                Nós, mestres dos dados previmos que você teria uma promissora trajetória como herói (ou será como vilão?), e por isso decidimos doutrina-lo em um dos mais antigos testamentos nerds, o D&D. Então o que estamos esperando para começar?
            </p>
        </section>
        <section id="Regras">
            <h1>Regras</h1>
            <p>
                Como eu disse, apesar de parecer uma bagunça, RPG tem regras, mas a maior regra é a diversão, então vale sempre conversa com seu mestre ou jogadores para ver se cabe uma modificação nas regras propostas pelo livro, essas alterações nas regras são chamadas de “Homebrews” ou regras da casa e existem desde a primeira mesa de RPG.
            </p>
            <p>
                o D&D é um sistema d20, ou seja, suas principais ações acontecem em torno do rolamento de um dado d20. É simples, o mestre narra uma situação, o jogador diz o que quer fazer, o mestre solicita um teste (pede para rolar um dado de determinado atributo), o jogador rola o dado e o valo tirado (de 1 a 20) irá definir se ele foi bem ou mal sucedido na sua ação. O básico é isso, porém existem fatores que interferem e muito nessas ações, como o atributo testado para realizar determinado ato, por exemplo, alguns personagens tem mais força física que outros, logo, tem mais facilidade para realizar atos que necessitam de força, e o sistema possui uma forma de calcular essas facilidades e dificuldades se baseando na ficha do personagem que é o que descreve seu “herói”. Outro fator que causa grande impacto na suas ações é o seu turno, isso é para definir o tempo das suas ações, em um combate o turno de cada personagem (isso é o tempo que cada personagem tem para realizar suas ações) costumar ser de alguns segundos, mas confie em mim, um Orc com uma clava na mão consegue fazer estragos grandiosos em alguns segundos, é como diria o grade Gandalf: “Tudo o que temos é decidir o que fazer com tempo que nos é dado”. 
            </p>
            <p>
                Um fator indispensável em uma aventura são os pontos de vida (HP), dano e pontos de experiência (XP). Como o nome sugere o HP define a vida dos personagens, tendo um valor máximo que varia da raça, classe e nível do personagem, já o dano é o que vai ameaçar reduzir o HP, reduzindo a cada ataque bem sucedido ou efeito causado um valor muitas vezes tirado no dado (com dados diferentes para danos diferentes). O XP é o que vai possibilitar seu personagem subir de nível, e isso pode ser calculado por uma pontuação que aumenta a cada desafio superado ou de acordo com a evolução da história, quem decide é o mestre.
            </p>
            <p>
                Para poder ver as principais regras de um jogo de RPG <a href="Regras.html">acesse esse link</a> e veja uma coletânea que reunimos após ler muitos pergaminhos antigos e decifrar runas esquecidas.
            </p>
        </section>
        <section id="Raças-e-Classes">
            <h1>Raças e Classes</h1>
            <p>
                Bem, falar de jogos de RPG é falar de imaginação, como já mencionamos, então por nos limitarmos a viver vidas humanas e nos ater a um único ofício sem criatividade? Não há motivos, para isso que servem as Raças e as Classes.
            </p>
            <h2>Raças</h2>
            <img src="imgs/imgraças/IMG-20220627-WA0034.jpg" alt="" class="animação">
            
            <p class="narração">
                “Imagine você, entrando em uma cidade, atravessa os grande portão dela, sente aquele cheiro típico das grandes cidades, cheiro de gente, das cozinhas, das especiarias do mercado e do saneamento precário. Você anda pelas ruas de calçamento da cidade e percebe que as pessoas te encaram, não com desprezo, sim com fascínio, com curiosidade. São pessoas de todo tipo, Elfos, Anões, Halflings, mas olhando bem você entende o motivo do interesse deles por você, você é o único humano.”
            </p>
            <p>
                O universo de um RPG é repleto por diversos tipos seres e criaturas, desses cada um interage de forma diferente com meio. Escolher qual a raça do seu personagem, além do fator estético, ajuda a definir e características dele, tanto físicas como comportamentais. Um Anão por exemplo, costuma ser forte, com uma constituição invejável, um gênio difícil de lidar mas de índole leal, uma vez conheci um, dizia que seu lar e a riqueza de sua família tinha sido roubado por um dragão e que agora estava em uma jornada para recuperar o que era seu por direito, ele, mais os 12 anões que o acompanhavam tinham exatamente esse perfil, fortes, destemidos e leais. Para saber mais sobre as raças clique na imagem. 
            </p>
            <h2>Classes</h2>
            <img src="imgs/imgraças/IMG-20220627-WA0035.jpg" alt="" class="animação">
            
            <p class="narração">
                “Um grupo explora uma masmorra, são quatro pessoas, um ladino, um paladino, um bárbaro e bruxo. Eles avançam com calma, seguindo a formação da ordem que foram citados, o lugar é escuro e tem um cheiro fétido, o bruxo já está ficando nauseado, o paladino segue convicto no objetivo inicial do grupo, o ladino está concentrado em identificar armadilhas e o bárbaro já está sem paciência com o vagaroso avanço, o objetivo deles é encontrar um companheiro de aventura que foi sequestrado por goblins. Nesse ritmo não demora muito para o bárbaro tomar a iniciativa da empreitada e seguir o caminho ignorando todas as armadilhas, nisso tudo vira o maior caos, são flechas envenenadas voando, magias sendo ativadas, inimigos sendo alertados, mas enfim, com as magias do bruxo, a força do bárbaro, a habilidade do paladino e a astúcia do ladino todos chegam à última sala da masmorra porém lá tem uma desagradável surpresa, ou nem tanto. Eles não encontram seu amigo mas encontram um sarcófago cheio de tesouros. O bruxo acha uma má ideia saquear o sarcófago por causa das possíveis maldições, o paladino acha mais importante continuar a busca, o ladino observa possíveis armadilhas e está tentado a pegar o tesouro e o bárbaro. Qual será a continuação da história?”
            </p>
            <p>
                As classes são uma mecânica muito importante em um RPG, elas definem muitas características dos personagens, elas dizem por exemplo as proficiências deles, como interagem com o com o mundo, como se comportam a mais diversas situações e também fala muito sobre a índole deles, por exemplo, é um guerreiro divino que jura defender a justiça. Existem diversas classes, com subclasses e combinações que chamamos de multiclasse, para saber mais clique no bonequinho.
            </p>
        </section>
        <section id="encerramento">
            <h1>E agora? Pronto para começar sua jornada?</h1>
            <p>
                Bem, te demos o melhor equipamento que poderíamos te dar, o conhecimento. ágora vá, a Terras Intermédias precisam de você maculado (não, dessa vez não é referência ao Senhor dos Anéis, na verdade é uma referência a algo que faz referência a Senhor dos Anéis), mas antes, pegue um saco de moedas, suprimentos, uma montaria, armas (porquê nem todos o oponentes vão se ferir com apenas com o seu conhecimento), reúna um gruo de bravos amigos e partiu se aventurar por esse mundo incrível.</p>
            <p>
                Para te ajudar nessa tarefa preparámos uma página onde você poderá criar uma ficha quem nem os antigos feiticeiros criavam, basta <a href="mandaparaapaginadecomomontarficha">acessar esse link</a>. Caso queira uma maneira mais rápida tem uma magia incrível criada pelos Elfos que te permite criar uma ficha de personagem rapidamente, o nome dessa magia é D&D Beyond e você pode acessa-la <a href="https://www.dndbeyond.com/characters">por aqui</a> (te garanto que ela ajuda muito).
            </p>
            <h2 id="frasefinal">Agora tome cuidado com os Orcs, não roube dragões sem um bom motivo e/ou bom disfarce e… acima de tudo… divirta-se!</h2>
        </section>
        
    </main>
    <footer>
        <img id="imagem-de-dado" src="imgs/dado-rodapé.png" alt="imagem de um dado">
    </footer>
    
    
    <script>
        
        function desaparece(){
            let transit = document.getElementById('inicio');
            if(transit.classList.contains('move')){
                transit.classList.add('mostra');
                transit.classList.remove('move');

            }
            
        }
    </script>
</body>
</html>
